services:
  mysql-consultas:
    image: mysql:8.0
    container_name: mysql-consultas
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: marcador_consultas
      MYSQL_USER: usuario
      MYSQL_PASSWORD: senha123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
